#!/usr/bin/with-contenv bash

[[ ! -d /config/organizr/.git ]] && (git clone https://github.com/causefx/Organizr /config/organizr/)

# Create Config file (else fail2ban will not launch)
if [ ! -e "/config/organizr/loginLog.json" ] ; then
    touch "/config/organizr/loginLog.json"
fi